CREATE TABLE hero (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE hero_role (
    id BIGINT NOT NULL AUTO_INCREMENT,
    hero_id BIGINT NOT NULL,
    role INT NOT NULL,

    PRIMARY KEY (id)
);

